import type { Metadata } from "next";
import Search from "./components/search";
import Filter from "./components/Filter";
import Sort from "./components/Sort";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="min-h-full flex flex-col">
        <Search />
        <Filter />
        <Sort />
        {children}
        </body>
    </html>
  );
}
